package server

import (
	"fmt"
	"strings"
)

// SyncTraefik regenerates the Traefik dynamic-config file (TraefikFile) with
// one exact HostSNI rule per registered domain. Traefik v2 does not support
// wildcard HostSNI, but its file provider hot-reloads on change, so the
// server rewrites this file whenever a domain is registered and Traefik
// starts passing that subdomain's TLS through within a second.
func (s *Server) SyncTraefik() error {
	if s.cfg.TraefikFile == "" {
		return nil
	}
	// Concurrent claims must not interleave writes, nor let a rename built
	// from an older domain list land last and drop a newer domain.
	s.syncMu.Lock()
	defer s.syncMu.Unlock()

	rules := []string{fmt.Sprintf("HostSNI(`%s`)", s.cfg.Domain)}
	for _, d := range s.state.Domains() {
		rules = append(rules, fmt.Sprintf("HostSNI(`%s.%s`)", d, s.cfg.Domain))
	}

	var b strings.Builder
	b.WriteString("# Generated by tunler-server. Do not edit; regenerated on every domain registration.\n")
	b.WriteString("tcp:\n")
	b.WriteString("  routers:\n")
	b.WriteString("    tunler:\n")
	b.WriteString("      entryPoints:\n")
	b.WriteString("        - websecure\n")
	fmt.Fprintf(&b, "      rule: %s\n", strings.Join(rules, " || "))
	b.WriteString("      service: tunler\n")
	b.WriteString("      tls:\n")
	b.WriteString("        passthrough: true\n")
	b.WriteString("  services:\n")
	b.WriteString("    tunler:\n")
	b.WriteString("      loadBalancer:\n")
	b.WriteString("        servers:\n")
	b.WriteString("          - address: \"tunler:443\"\n")

	return writeFileAtomic(s.cfg.TraefikFile, []byte(b.String()), 0o644)
}
